[build]
  publish = "public"
  command = "gatsby build"
[context.production]
  environment ={  KONTENT_PROJECT_ID = "f92b9105-97eb-0067-8e88-c950c929fb59", KONTENT_LANGUAGE_CODENAMES = "default" }